members/urls.py
from django.contrib import admin
from django.urls import path
from members.views import *
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

app_name = 'members'

urlpatterns = [
    path('home/', home, name="home"),
    path('login',login_page,name="login_page"),
    path('register/', register_page, name='register_page'),
      
]
# #Serve media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# #Serve static files
urlpatterns += staticfiles_urlpatterns()      

ordex/urls.py
from django.contrib import admin
from django.urls import path,include
from  django.views.generic.base import TemplateView 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('order_register.urls')),
    path('',TemplateView.as_view(template_name="home.html"), name="home"), 
    path('members/', include('members.urls')),
    path('members/', include('django.contrib.auth.urls')),  # For login/logout views
    path('api_auth/', include('rest_framework.urls'))
]

members/models.py
from django.db import models
from django.contrib.auth.models import User

members/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

def home(request):
    return render(request, 'login.html')

def login_page(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        #Checks of a user with the provided username exits
        if not User.objects.filter(username=username).exists():
        #Display an error message if the username does not exit
         messages.error(request,'Invalid Username')
         return redirect('/login/') #might needed changing
    
        user =  authenticate(username=username, password=password)

        if user is None:
        #Display and error message if authentication fails (invalid password)
          messages.error(request, "Invalid Password")
          return redirect('login_page')
        else:
            login(request, user)
            return redirect('home')
        
    return render(request, 'login.html')

#View function for registration page
def register_page(request):
   if request.method == 'POST' :
      first_name =  request.POST.get('first_name')
      last_name = request.POST.get('last_name')
      username = request.POST.get('username')
      password = request.POST.get('password')

      #check if a user with the provided username already exits
      user = User.objects.filter(username=username)

      if user.exists():
         messages.info(request, "Username already taken")
         return redirect('register_page')
      
      user = User.objects.create_user(
         first_name = first_name,
         last_name=last_name,
         username=username       
    )
      user.set_password(password)
      user.save()

      messages.info(request, "Account created Sucessfully")
      return redirect('register_page')
   
   return render(request, 'register.html')

             

members/templates/login.html
{% extends "order_register/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Login</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
    <div class="container mt-5">
        <form class="col-6 mx-auto card p-3 shadow-lg" method="post" enctype="multipart/form-data">
            <h1 style="text-align: center;"><span style="color: dodgerblue;">Ordex</span></h1>

            {% csrf_token %}

            <h3>Login</h3>
            <hr>

            {% if messages %}
            <div class="alert alert-primary" role="alert">
                {% for message in messages %}
                {{ message }}
                {% endfor %}
            </div>
            {% endif %}

            <div class="form-group">
                <label for="exampleInputEmail1">Username</label>
                <input type="text" class="form-control" name="username" id="exmapleInputEmail1" aria-describedby="emailHelp" placeholder="Enter username" required >
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="password" required />
            </div>

            <p>Don't have an account <a href="{%url 'members:register_page' %}">Register</a>  </p>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>


    </div>
     


</body>
</html>

{% endblock %}

members/templates/register.html
{% extends "order_register/base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
<head>
<title>Registration Form</title>
</head>

    
        <form class="col-6 mx-auto card p-3 shadow-lg" method="post" enctype="multipart/form-data">
          
            {% csrf_token %}

            <h1 style="text-align: center;"><span style="color: dodgerblue">Ordex</span></h1>
            <h3>Register</h3>
            <hr>

            {% if messages %}
            <div class="alert alert-primary" role="alert">
                {% for message in messages %}
                {{ message }}
                {% endfor %}
            </div>
            {% endif %}

            <div class="form-group">
                <label for="exampleInputEmail1">First name</label>
                <input type="text" class="form-control" name="first_name" id="exmapleInputEmail1" aria-describedby="emailHelp" placeholder="Enter First name" required>
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Last name</label>
                <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Last name" required />
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Username</label>
                <input type="text" class="form-control" name="username" id="exmapleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" required>
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="password" required />
            </div>

            <p>Already have an account <a href="{%url 'members:login_page' %}">Login</a>  </p>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>




{% endblock %}